[package]
name = "typedpack"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[dependencies]
rmpv = { version = "1", features = ["with-serde"] }
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
serde_repr = "0.1"
