[package]
name = "typedpack-tests"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[dependencies]
rmp-serde = "1.3.0"
serde = "1.0.228"
typedpack.workspace = true

[build-dependencies]
typedpack-codegen.workspace = true
