[package]
name = "typedpack-cli"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4.5.53", features = ["cargo"] }
thiserror = "2.0.17"
typedpack-codegen.workspace = true
